plugins { id 'com.android.application' }

android {
  namespace 'com.everya.offline'
  compileSdk 34
  defaultConfig {
    applicationId 'com.everya.offline'
    minSdk 24
    targetSdk 34
    versionCode 7
    versionName '5.0.0'
  }
  buildTypes {
    release {
      minifyEnabled false
    }
  }
}
